### ISSUE TITLE
I can`t call tornet in windows python (3.11.9)

### ISSUE THREAD

**Issue by falwe** [ByteBreach/tornet#2]
i`m trying to call tornet on cmd, but tornet says error, here`s log:
```PS C:\Users\pine9\Downloads\xwaf-master\xwaf-master> tornet --interval 5 --count 0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\pine9\AppData\Roaming\Python\Python311\Scripts\tornet.exe\__main__.py", line 7, in <module>
  File "C:\Users\pine9\AppData\Roaming\Python\Python311\site-packages\tornet\tornet.py", line 127, in main
    signal.signal(signal.SIGQUIT, signal_handler)
                  ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGQUIT'
```

**Comment by mrfidal** [comment]
Sorry for the late reply. I'm working on fixing this immediately. 😊

**Comment by mr-fidal** [comment]
use linux 
parrot , kali , etc...
